name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run lint
    - run: |
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "CODEBASE_URL=${{ vars.CODEBASE_URL }}" >> .env
        echo "EMAIL=${{ vars.EMAIL }}" >> .env
        echo "LINKEDIN_URL=${{ vars.LINKEDIN_URL }}" >> .env
        echo "MONGODB_ABOUT_COLLECTION=${{ vars.MONGODB_ABOUT_COLLECTION }}" >> .env
        echo "MONGODB_CERTIFICATIONS_COLLECTION=${{ vars.MONGODB_CERTIFICATIONS_COLLECTION }}" >> .env
        echo "MONGODB_EXPERIENCES_COLLECTION=${{ vars.MONGODB_EXPERIENCES_COLLECTION }}" >> .env
        echo "MONGODB_PUBLICATIONS_COLLECTION=${{ vars.MONGODB_PUBLICATIONS_COLLECTION }}" >> .env
        echo "MONGODB_DATABASE=${{ vars.MONGODB_DATABASE }}" >> .env
        echo "PHONE_NUMBER=${{ vars.PHONE_NUMBER }}" >> .env
    - run: npm run build
    - run: npm run test
